# Generated by Django 5.0 on 2026-04-12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publie')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('auteur', models.CharField(max_length=100, verbose_name='Auteur')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
    ]
